[build]
base = "/"
publish = "frontend/dist/frontend/browser"
command = "cd frontend && npm install && npm run build && cd ../backend && npm run update"


[functions]
directory = "backend/netlify/functions"
included_files = ["backend/data/*.json", 'backend/images/**']

