[build]
base = "/"
publish = "frontend/dist/frontend/browser"
command = "cd frontend && npm install && npm run build && cd ../backend && npm run update"


[functions]
directory = "backend/netlify/functions"


[build.environment]
NETLIFY_CACHE_CONTROL = "no-cache"

[[build.processing]]
# Copy the data folder to the netlify functions directory
command = "cp -R backend/data backend/netlify/functions/data"