[build]
base = "/"
publish = "dist/frontend/browser"
command = "cd frontend && npm install"


[functions]
directory = "backend/netlify/functions"
included_files = ["backend/data/*.json", 'backend/images/**']

