[build]
base = "/"
publish = "frontend/dist/frontend"
command = "cd frontend && npm install && npm run build && cd ../backend && npm run update"


[functions]
directory = "backend/netlify/functions"


